In [ ]:
import torch # Importing library PyTorch
import numpy as np

import pandas as pd

# **Trabajando con tensores**

In [ ]:
torch.__version__

'1.7.0+cu101'

### Inicializando tensores

In [ ]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[2.1320e-35, 0.0000e+00],
        [1.5975e-43, 1.3873e-43]])


tensor([[0.0261, 0.5026],
        [0.1177, 0.3000]])

In [ ]:
tensor_c = torch.rand(2, 2)
print(tensor_c)

tensor([[0.0898, 0.0297],
        [0.1475, 0.5354]])


In [ ]:
result = tensor_b + tensor_c
result

tensor([[0.1159, 0.5323],
        [0.2652, 0.8354]])

In [ ]:
result.shape
reshaped = result.view(4, 1)
reshaped

tensor([[0.1159],
        [0.5323],
        [0.2652],
        [0.8354]])

In [ ]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(points)
points[0][1] = 28.0
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 1., 28.],
        [ 3.,  4.]])


 1.0
 28.0
 3.0
 4.0
[torch.FloatStorage of size 4]

In [ ]:
points, points.stride()

(tensor([[ 1., 28.],
         [ 3.,  4.]]), (2, 1))

In [ ]:
p_t = points.t() # Trasponiendo el tensor
p_t, p_t.stride() 

(tensor([[ 1.,  3.],
         [28.,  4.]]), (1, 2))

In [ ]:
tensor_x = torch.tensor([1, 2, 3, 4])
tensor_x, torch.unsqueeze(tensor_x, 0) #Agregando dimension de forma horizontal
tensor_x, torch.unsqueeze(tensor_x, 1) #Agregando dimension de forma vertical

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [ ]:
numpyArray = np.random.randn(2, 2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[ 0.7858, -1.1199],
        [ 0.7664,  0.3463]], dtype=torch.float64)

# **Representar datos con tensores**

In [ ]:
# Media Aritmetica en Tensores
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[ 0.7858, -1.1199],
        [ 0.7664,  0.3463]], dtype=torch.float64)
tensor(0.1946, dtype=torch.float64)
tensor([ 0.7761, -0.3868], dtype=torch.float64)
tensor([-0.1671,  0.5563], dtype=torch.float64)


In [ ]:
# Desviacion estandar
torch.std(from_numpy, dim=1)

tensor([1.3475, 0.2970], dtype=torch.float64)

In [ ]:
# Almacenando tensores en archivo
torch.save(from_numpy, 'tensor.t')

In [ ]:
# Recuperando tensor almacenado en archivo
load = torch.load('tensor.t')
load

tensor([[ 0.7858, -1.1199],
        [ 0.7664,  0.3463]], dtype=torch.float64)

# Load Data

In [ ]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [ ]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [ ]:
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot', 'Skill Moves']].dropna(axis=0, how='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [ ]:
data = players[:, 1:]
data, data.shape
target = players[:, 0]

In [ ]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
good
average

tensor([[22.,  2.,  3.,  2.],
        [23.,  2.,  3.,  2.],
        [25.,  3.,  2.,  3.],
        ...,
        [24.,  1.,  3.,  3.],
        [25.,  1.,  3.,  3.],
        [33.,  1.,  3.,  3.]])